name: pubsub
version: 1.1.6
author: Dj Gilcrease <digitalxero@gmail.com>
description: Async implementation of pubsub that allows for hierarchical categorical publish and subscribe
homepage: https://github.com/Digitalxero/dart-pubsub
documentation: https://github.com/Digitalxero/dart-pubsub
dependencies:
  dynamic_object: any
dev_dependencies:
  unittest: any
