name: pubsub
version: 1.1.4
author: Dj Gilcrease <digitalxero@gmail.com>
description: Async hierarchical pubsub library, modeled after https://github.com/KanbanSolutions/jquery-pubsub
homepage: https://github.com/Digitalxero/dart-pubsub
documentation: https://github.com/Digitalxero/dart-pubsub
dependencies:
  dynamic_object: any
dev_dependencies:
  unittest: any
